### ISSUE TITLE
The description about waterfall is not correct

### ISSUE THREAD

**Issue by xavierchow** [promise-nuggets/promise-nuggets.github.io#9]
https://github.com/promise-nuggets/promise-nuggets.github.io/blob/src/src/documents/articles/12-doing-things-in-series.html.md
> The callback is called with no error and an array of results after all operations are complete, or when the first error is encountered.

I believe the callback of [waterfall](https://github.com/caolan/async#waterfalltasks-callback) gets the last task's result rather than an array of results(that's what `series`'s callback gets).
Will make a PR for it.

**Comment by spion** [comment]
Right! Thanks for the fix!
